<footer class="page-footer font-small bg-dark pt-4">
	<div class="container-fluid text-center text-md-left">
      <div class="row">
        <hr class="clearfix w-100 d-md-none pb-3">
          <div class="col-md-3 mb-3">
            <h3 class="text-uppercase text-light px-3">Digital Nomad</h3>
            <ul class="list-unstyled px-3 py-3">
              <li>
                <a href="index.php">Home</a>
              </li>
              <li>
                <a href="citiestoexplore.php">Citites to explore</a>
              </li>
              <li>
                <a href="gallery.php">Gallery</a>
              </li>
              <li>
                <a href="jobs.php?jt=job">Jobs</a>
              </li>
            </ul>
          </div>
      </div>
    </div>
    <div class="footer-copyright text-center text-light py-3">© Vipuldeep S. Gulati</div>
  </footer>